export enum PreferredColorScheme {
  LIGHT = "light",
  DARK = "dark",
}

export enum ProjectCategory {
  ALL = "all",
  BACKEND = "backend",
  DESKTOP = "desktop",
  DEVOPS = "devops",
  FRONTEND = "frontend",
  MACHINE_LEARNING = "machine-learning",
  OPEN_SOURCE = "open-source",
  POSTERS = "posters",
  PUBLICATIONS = "publications",
  VOLUNTEERING = "volunteering",
}
export enum MediaCategory {
  ALL = "all",
  CONFERENCE_TALKS = "talks",
  WORKSHOPS = "workshops",
  PODCAST = "podcast",
  WEBINARS = "webinars",
  INTERVIEWS = "interviews",
  TUTORIAL_VIDEOS = "tutorial-videos",
}

export enum ProjectTag {
  Ruby = "Ruby",
  GDAL = "Gdal",
  Python = "Python",
  FastAPI = "FastAPI",
  STAC = "STAC",
  PostGIS = "PostGIS",
  Geoserver = "Geoserver",
  React = "React",
  MaplibreGLJS = "Maplibre GL JS",
  Leaflet = "Leaflet",
  Django = "Django",
  NextJS = "Next JS",
  TypeScript = "TypeScript",
  AWS = "AWS",
  GCP = "GCP",
  GitHubActions = "GitHub Actions",
  DigitalOcean = "Digital Ocean",
  Geodjango = "Geodjango",
  Celery = "Celery",
  TailwindCSS = "Tailwind CSS",
  More = "and more",
  Stripe = "Stripe",
  Redis = "Redis",
  MVT = "MVT",
  Geonode = "Geonode",
  Rust = "Rust",
  DeckGL = "DeckGL",
  WebSocket = "Websockets",
  CSS3 = "CSS3",
  SQL = "SQL",
  OpenStreetMap = "OpenStreetMap",
  Mapathon = "Mapathon",
  YouthMappers = "YouthMappers",
  ArcGIS = "ArcGIS",
  DSAS = "DSAS",
  GEE = "GEE",
  RemoteSensing = "Remote Sensing",
  DeepLearning = "Deep Learning",
  TeamWork = "Team Work",
}
